# Generated by Django 5.1.1 on 2024-10-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='category')),
                ('title', models.CharField(max_length=255)),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='course')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('bignner', 'Bignner'), ('medium,', 'Medium'), ('expert', 'expert')], default='bignner', max_length=255)),
                ('learnings', models.TextField(help_text="text must  be ',' separeted ")),
                ('type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='paid', max_length=255)),
                ('old_price', models.PositiveIntegerField()),
                ('base_price', models.PositiveBigIntegerField()),
            ],
        ),
    ]
