# Generated by Django 5.1.1 on 2024-10-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
