# Generated by Django 5.1.1 on 2024-10-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('biggner', 'Biggner'), ('medium,', 'Medium'), ('expert', 'expert')], default='bignner', max_length=255),
        ),
    ]
