# Generated by Django 5.1.1 on 2024-10-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='base_price',
            new_name='new_price',
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('biggner', 'Biggner'), ('expert,', 'Expert'), ('advanced', 'advanced')], default='bignner', max_length=255),
        ),
    ]
