# Generated by Django 5.1.1 on 2024-10-10 09:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_rename_base_price_course_new_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('biggner', 'Biggner'), ('expert,', 'Expert'), ('advanced', 'advanced'), ('top_rated', 'Top Rated')], default='bignner', max_length=255),
        ),
        migrations.CreateModel(
            name='Lessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lession', to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos')),
                ('video_link', models.URLField(blank=True, null=True)),
                ('durations', models.CharField(blank=True, max_length=255, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('lession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_lessions', to='course.lessions')),
            ],
        ),
    ]
