# Generated by Django 5.1.1 on 2024-10-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('biggner', 'Biggner'), ('expert', 'Expert'), ('advanced', 'Advanced'), ('top_rated', 'Top Rated')], default='bignner', max_length=255),
        ),
    ]
