# Generated by Django 5.1.1 on 2024-10-13 16:21

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ManyToManyField(blank=True, to='course.instructor'),
        ),
        migrations.CreateModel(
            name='Assingment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assignment')),
                ('title', models.CharField(max_length=255)),
                ('descripton', ckeditor.fields.RichTextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignment.acctachment')),
                ('start_time', models.DateField(blank=True, null=True)),
                ('end_time', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assginment', to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('title', models.CharField(max_length=255)),
                ('descripton', ckeditor.fields.RichTextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='project.attachment')),
                ('start_time', models.DateField(blank=True, null=True)),
                ('end_time', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_projects', to='course.course')),
            ],
        ),
    ]
