# Generated by Django 5.1.2 on 2024-10-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_rename_videos_lession_rename_lessions_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='payment_id',
            field=models.CharField(default='', max_length=25555),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_method',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
