# Generated by Django 5.1.2 on 2024-10-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_completelession_delete_iswatched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completelession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
