# Generated by Django 5.1.1 on 2024-10-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0015_rename_videos_lession_rename_lessions_module_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_for_all', models.BooleanField(default=False)),
                ('specific_course', models.ManyToManyField(blank=True, to='course.course')),
            ],
        ),
    ]
