# Generated by Django 5.1.1 on 2024-10-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='parcentige',
            field=models.IntegerField(default=0),
        ),
    ]
