# Generated by Django 5.1.1 on 2024-10-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_title_coupon_cupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='parcentige',
            new_name='discount_parcentige',
        ),
    ]
