# Generated by Django 5.1.2 on 2024-10-20 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_enrollment_payment_id_enrollment_payment_method'),
        ('payments', '0005_rename_coupon_cupon_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_course', to='course.course'),
        ),
    ]
