# Generated by Django 5.1.1 on 2024-10-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
